service: streaming-hell-telegram-bot
provider:
  name: aws
  runtime: nodejs10.x
  profile: serverless
  memorySize: 128
  timeout: 20
  versionFunctions: true
  tracing:
    lambda: true
  stage: prod
  region: eu-north-1
package:
  exclude:
    - src/**
functions:
  main:
    handler: dist/index.handler
    events:
      - http:
          path: webhook
          method: post
    environment:
      TOKEN: ${env:TOKEN}
      MIXPANEL_TOKEN: ${env:MIXPANEL_TOKEN}
    tags:
      PROJECT: streaming-hell
