service: streaming-hell-api

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs10.x
  profile: serverless
  stage: ${opt:stage}
  region: eu-north-1
  memorySize: 128
  apiKeys:
    - name: prod-streaming-hell-telegram-bot
      value: ${env:API_GATEWAY_KEY_TELEGRAM_BOT_PROD}
      description: Key for telegram bot access

functions:
  linksByUrl:
    handler: dist/main.linksByUrl
    events:
      - http:
          path: linksByUrl
          method: GET
          private: true
    environment:
      SONGLINK_API_KEY: ${env:SONGLINK_API_KEY}
    tags:
      PROJECT: streaming-hell

custom:
  # API Gateway domain
  customDomain:
    domainName: api.streaming-hell.com
    stage: ${self:provider.stage}
    basePath: v1
    certificateName: '*.streaming-hell.com'
    createRoute53Record: true
    endpointType: 'edge'
    securityPolicy: tls_1_2
